[package]
name = "logseq-gardener"
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
description = "A command-line tool for Logseq Markdown gardens"
license = "AGPL-3.0-only"
repository = "https://github.com/codekiln/logseq-gardener"

[[bin]]
name = "lsg"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dist]
inherits = "release"
lto = "thin"
