#!/usr/bin/env bash
#MISE description="Run Clippy with warnings denied"
#USAGE flag "-h --help" help="Show task help"
set -euo pipefail

cargo clippy --locked --workspace --all-targets --all-features -- -D warnings
